import type { Skill } from '../types'

export const SKILLS: Skill[] = [
  { id: 'CALCULUS_TUTORING', label: 'Calculus tutoring', category: 'tutoring' },
  { id: 'CS_TUTORING', label: 'CS tutoring', category: 'tutoring' },
  { id: 'PHYSICS_TUTORING', label: 'Physics tutoring', category: 'tutoring' },
  { id: 'WRITING_HELP', label: 'Writing help', category: 'tutoring' },
  { id: 'GEL_MANICURE', label: 'Gel manicure', category: 'beauty' },
  { id: 'NAIL_ART', label: 'Nail art', category: 'beauty' },
  { id: 'HAIRCUT', label: 'Haircut', category: 'beauty' },
  { id: 'BRAIDS', label: 'Braids', category: 'beauty' },
  { id: 'AIRPORT_RIDE', label: 'Airport ride', category: 'rides' },
  { id: 'GROCERY_RUN', label: 'Grocery run', category: 'rides' },
  { id: 'CAMPUS_RIDE', label: 'Campus ride', category: 'rides' },
  { id: 'LOGO_DESIGN', label: 'Logo design', category: 'creative' },
  { id: 'FLYER_DESIGN', label: 'Flyer design', category: 'creative' },
  { id: 'PHOTOGRAPHY', label: 'Photography', category: 'creative' },
  { id: 'VIDEO_EDITING', label: 'Video editing', category: 'creative' },
  { id: 'PYTHON_HELP', label: 'Python help', category: 'tech' },
  { id: 'WEB_DEV', label: 'Web development', category: 'tech' },
  { id: 'RESUME_REVIEW', label: 'Resume review', category: 'tech' },
  { id: 'EXCEL_HELP', label: 'Excel help', category: 'tech' },
  { id: 'GYM_SPOTTER', label: 'Gym spotter', category: 'fitness' },
  { id: 'WORKOUT_PLAN', label: 'Workout plan', category: 'fitness' },
  { id: 'HOME_COOKING', label: 'Home cooking', category: 'food' },
  { id: 'BAKING', label: 'Baking', category: 'food' },
  { id: 'GUITAR_LESSON', label: 'Guitar lesson', category: 'music' },
  { id: 'PIANO_LESSON', label: 'Piano lesson', category: 'music' },
]
